server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-otm6ngfq.sql.tencentcdb.com:21667/mall?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 8030016-Bjut

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml